// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQwx6aFcd7xpDKo5QQAZdhvabtWO_M13U',
    appId: '1:928352644478:web:0a36b52e2b8ab04f18572f',
    messagingSenderId: '928352644478',
    projectId: 'appmiaged',
    authDomain: 'appmiaged.firebaseapp.com',
    databaseURL: 'https://appmiaged-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appmiaged.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc2btIKCQF5TYXOW0EoNH3W635IYisA8o',
    appId: '1:928352644478:android:11172839188ae8f518572f',
    messagingSenderId: '928352644478',
    projectId: 'appmiaged',
    databaseURL: 'https://appmiaged-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appmiaged.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbTpUx4OfGvA2uKwd8_HARsSG4TMibbPs',
    appId: '1:928352644478:ios:3ef22f79d2ecf93518572f',
    messagingSenderId: '928352644478',
    projectId: 'appmiaged',
    databaseURL: 'https://appmiaged-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appmiaged.appspot.com',
    iosClientId: '928352644478-f49jn6nfojtej82co7sa6kh491eaqo16.apps.googleusercontent.com',
    iosBundleId: 'com.example.appmiagedelias',
  );
}
